apiVersion: v2
name: Dw4Otk
version: 0.0.1
appVersion: 0.1.0
description: A Helm chart for Kubernetes
type: application

dependencies:
  - name:  twilhelm
    version: 1.1.0
    repository: "oci://018537234677.dkr.ecr.us-east-1.amazonaws.com/github.com/twilio-internal/twilio-helm-library"
